name: Deploy PHP App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy PHP App to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Update and install required packages
          sudo yum update -y
          sudo yum install -y httpd php php-mysqli git mysql57

          # Start and enable Apache
          sudo systemctl start httpd
          sudo systemctl enable httpd

          # Move to web directory
          cd /var/www/html

          # Clean up old files
          sudo rm -rf *

          # Clone latest code from GitHub
          sudo git clone https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPOSITORY.git app

          # Move files to the correct location
          sudo mv app/src/* .
          sudo mv app/slt_clothing_db.sql .

          # Remove temporary folder
          sudo rm -rf app

          # Restart Apache to apply changes
          sudo systemctl restart httpd
          EOF

      - name: Import Database
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Ensure MySQL Client is installed
          sudo yum install -y mysql57

          # Import the database schema
          mysql -h slt-clothing-db.c18qswy2ixqk.us-east-1.rds.amazonaws.com -u admin -psltclothing12345 -e "CREATE DATABASE IF NOT EXISTS slt_clothing_db;"
          mysql -h slt-clothing-db.c18qswy2ixqk.us-east-1.rds.amazonaws.com -u admin -psltclothing12345 slt_clothing_db < /var/www/html/slt_clothing_db.sql
          EOF
